version: '3'
services:
    beat:
        image: docker.elastic.co/apm/apm-server:7.0.1
        ports:
          - "8200:8200"
          - "8201:8200"
        environment:
          - apm-server.host=0.0.0.0
        #volumes:
        #    - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
        networks:
          - kelha
        depends_on:
          - elasticsearch
          - kibana
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        # volumes:
        #     - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        volumes:
          - ./elasticdata:/usr/share/elasticsearch/data
        environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
        networks:
          - kelha
        ports:
          - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.0.1
        # volumes:
        #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
          - "5601:5601"
        networks:
          - kelha
        environment:
          - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
          - elasticsearch

    heartbeat:
        image: docker.elastic.co/beats/heartbeat:7.0.1
        volumes:
          - ./heartbeat.yml:/usr/share/heartbeat/config/heartbeat.yml
        networks:
          - kelha
        depends_on:
          - elasticsearch
          - kibana

    logstash:
        image: docker.elastic.co/logstash/logstash:7.0.1
        #volumes:
        #  - ./config/logstash/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
        ports:
          - "5000:5000"
          - "9600:9600"
        networks:
          - kelha
        depends_on:
          - elasticsearch

networks:
  kelha:
    driver: bridge
    
volumes:
  elasticdata:
