version: '3'
services:
    #beat:
        #image: docker.elastic.co/apm/apm-server:${VERSION}
        #ports:
        #  - "8200:8200"
        #  - "8201:8200"
        #environment:
        #  - apm-server.host=0.0.0.0
        #volumes:
        #    - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
        #networks:
        #  - kelha
        #depends_on:
        #  - elasticsearch
        #  - kibana
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
        volumes:
             - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
             - ./elasticdata:/usr/share/elasticsearch/data
        environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
        networks:
          - kelha
        ports:
          - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:${VERSION}
        # volumes:
        #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
          - "5601:5601"
        networks:
          - kelha
        environment:
          - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
          - elasticsearch
    heartbeat:
        image: docker.elastic.co/beats/heartbeat:${VERSION}
        command: -e --strict.perms=false
        volumes:
          - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
        networks:
          - kelha
        depends_on:
          - elasticsearch
          - kibana
    logstash:
        image: docker.elastic.co/logstash/logstash:${VERSION}
        #volumes:
        #  - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                    
        #- ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        ports:
          - "5044:5044"
        networks:
          - kelha
        depends_on:
          - elasticsearch

    app-search:
        image: docker.elastic.co/app-search/app-search:${VERSION}
        volumes:
          - ./app-search.yml:/usr/share/app-search/app-search.yml:ro
        ports:
          - "3002:3002"
        networks:
          - kelha
        depends_on:
          - elasticsearch

networks:
  kelha:
    driver: bridge
    
volumes:
  elasticdata:
