version: '3'

services:
    beat:
        image: docker.elastic.co/apm/apm-server:7.0.1
        ports:
            - "8200:8200"
            - "8201:8200"
        environment:
            - apm-server.host=0.0.0.0
        # volumes:
        #    - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
        networks:
            - elasticnet
        depends_on:
          - elasticsearch
          - kibana
   
   elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        # network_mode: "service:elasticsearch"
        # volumes:
        #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
        networks:
            - elasticnet
        ports:
            - "9200:9200"
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.0.1
        # volumes:
        #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
          - "5601:5601"
        networks:
            - elasticnet
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
          - elasticsearch
          
    #  heartbeat:
    #    image: docker.elastic.co/beats/heartbeat:7.0.1
     #   command: --strict.perms=false
     #   environment:
    #      - setup.kibana.host=kibana:5601
    #      - output.elasticsearch.hosts=["elasticsearch:9200"]
    # volumes:
    #   - ${PWD}/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    #     networks:
    #       - elasticnet

networks:
  elasticnet:
    driver: bridge
