heartbeat.monitors:
- type: http
  schedule: '@every 60s'
  urls:
    - https://nu.nl

- type: tcp
  schedule: '@every 120s'
  hosts:
    - elasticsearch:9200
    - kibana:5601

- type: icmp
  schedule: '@every 120s'
  hosts:
    - elasticsearch
    - kibana

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
